# Generated by Django 4.2.1 on 2023-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
